import os
import xml.etree.ElementTree as ET

translations = {
    'values-ar': {
        'vip_active': 'عضوية VIP نشطة',
        'vip_free_user': 'مستخدم مجاني',
        'vip_until': 'صالح حتى: %1$s',
        'vip_activated_at': 'تم التفعيل: %1$s',
        'vip_expires_at': 'تنتهي الصلاحية: %1$s',
        'vip_remaining': '%1$d يوم و %2$02d ساعة و %3$02d دقيقة و %4$02d ثانية',
        'vip_redeem_label': 'أدخل رمز VIP',
        'vip_redeem_hint': 'مثال: LOITP_30',
        'vip_redeem_button': 'تفعيل',
        'vip_watch_ad_3d': 'شاهد إعلانًا ← VIP لمدة 3 أيام',
        'vip_buy_30d_locked': 'شراء VIP لمدة 30 يومًا - قريبًا',
        'vip_buy_90d_locked': 'شراء VIP لمدة 90 يومًا - قريبًا',
        'vip_buy_1y_locked': 'شراء VIP لمدة عام - قريبًا',
        'vip_buy_lifetime_locked': 'شراء VIP مدى الحياة - قريبًا',
        'vip_restore_locked': 'استعادة المشتريات - قريبًا',
        'vip_revoke_all_button': 'إلغاء VIP',
        'vip_revoke_all_confirm_title': 'تأكيد الإلغاء',
        'vip_revoke_all_confirm_message': 'هل أنت متأكد أنك تريد إلغاء VIP والعودة إلى الحساب المجاني؟',
        'vip_entry_first_install': '🎁 هدية التثبيت الأول',
        'vip_entry_redeemed': 'VIP %1$d أيام',
        'vip_verifying_title': 'جاري التحقق…',
        'vip_success_title': 'نجاح',
        'vip_failed_title': 'فشل',
        'privacy_policy': 'سياسة الخصوصية',
        'confirm': 'تأكيد',
        'ok': 'موافق'
    },
    'values-de-rDE': {
        'vip_active': 'VIP Aktiv',
        'vip_free_user': 'Freier Benutzer',
        'vip_until': 'Gültig bis: %1$s',
        'vip_activated_at': 'Aktiviert am: %1$s',
        'vip_expires_at': 'Läuft ab am: %1$s',
        'vip_remaining': '%1$dd %2$02dh %3$02dm %4$02ds',
        'vip_redeem_label': 'VIP-Schlüssel eingeben',
        'vip_redeem_hint': 'z.B. LOITP_30',
        'vip_redeem_button': 'Aktivieren',
        'vip_watch_ad_3d': 'Anzeige ansehen → 3 Tage VIP',
        'vip_buy_30d_locked': '30 Tage VIP kaufen — Demnächst',
        'vip_buy_90d_locked': '90 Tage VIP kaufen — Demnächst',
        'vip_buy_1y_locked': '1 Jahr VIP kaufen — Demnächst',
        'vip_buy_lifetime_locked': 'Lebenslanges VIP kaufen — Demnächst',
        'vip_restore_locked': 'Kauf wiederherstellen — Demnächst',
        'vip_revoke_all_button': 'VIP entziehen',
        'vip_revoke_all_confirm_title': 'Entzug bestätigen',
        'vip_revoke_all_confirm_message': 'Sind Sie sicher, dass Sie VIP entziehen und zu einem kostenlosen Konto zurückkehren möchten?',
        'vip_entry_first_install': '🎁 Geschenk zur Erstinstallation',
        'vip_entry_redeemed': 'VIP %1$d Tage',
        'vip_verifying_title': 'Überprüfen…',
        'vip_success_title': 'Erfolgreich',
        'vip_failed_title': 'Fehlgeschlagen',
        'privacy_policy': 'Datenschutzerklärung',
        'confirm': 'Bestätigen',
        'ok': 'OK'
    },
    'values-es-rES': {
        'vip_active': 'VIP Activo',
        'vip_free_user': 'Usuario gratuito',
        'vip_until': 'Vence el: %1$s',
        'vip_activated_at': 'Activado: %1$s',
        'vip_expires_at': 'Expira: %1$s',
        'vip_remaining': '%1$dd %2$02dh %3$02dm %4$02ds',
        'vip_redeem_label': 'Ingresar clave VIP',
        'vip_redeem_hint': 'ej. LOITP_30',
        'vip_redeem_button': 'Activar',
        'vip_watch_ad_3d': 'Ver anuncio → 3 días VIP',
        'vip_buy_30d_locked': 'Comprar VIP de 30 días — Próximamente',
        'vip_buy_90d_locked': 'Comprar VIP de 90 días — Próximamente',
        'vip_buy_1y_locked': 'Comprar VIP de 1 año — Próximamente',
        'vip_buy_lifetime_locked': 'Comprar VIP de por vida — Próximamente',
        'vip_restore_locked': 'Restaurar compra — Próximamente',
        'vip_revoke_all_button': 'Revocar VIP',
        'vip_revoke_all_confirm_title': 'Confirmar revocación',
        'vip_revoke_all_confirm_message': '¿Está seguro de que desea revocar el VIP y volver a una cuenta gratuita?',
        'vip_entry_first_install': '🎁 Regalo de primera instalación',
        'vip_entry_redeemed': 'VIP %1$d Días',
        'vip_verifying_title': 'Verificando…',
        'vip_success_title': 'Éxito',
        'vip_failed_title': 'Fallido',
        'privacy_policy': 'Política de privacidad',
        'confirm': 'Confirmar',
        'ok': 'Aceptar'
    },
    'values-fr-rFR': {
        'vip_active': 'VIP Actif',
        'vip_free_user': 'Utilisateur gratuit',
        'vip_until': 'Expire le : %1$s',
        'vip_activated_at': 'Activé le : %1$s',
        'vip_expires_at': 'Expire le : %1$s',
        'vip_remaining': '%1$dj %2$02dh %3$02dm %4$02ds',
        'vip_redeem_label': 'Entrer la clé VIP',
        'vip_redeem_hint': 'ex. LOITP_30',
        'vip_redeem_button': 'Activer',
        'vip_watch_ad_3d': 'Regarder une pub → 3 jours VIP',
        'vip_buy_30d_locked': 'Acheter VIP 30 jours — Bientôt',
        'vip_buy_90d_locked': 'Acheter VIP 90 jours — Bientôt',
        'vip_buy_1y_locked': 'Acheter VIP 1 an — Bientôt',
        'vip_buy_lifetime_locked': 'Acheter VIP à vie — Bientôt',
        'vip_restore_locked': 'Restaurer l\'achat — Bientôt',
        'vip_revoke_all_button': 'Révoquer le VIP',
        'vip_revoke_all_confirm_title': 'Confirmer la révocation',
        'vip_revoke_all_confirm_message': 'Êtes-vous sûr de vouloir révoquer le VIP et revenir à un compte gratuit ?',
        'vip_entry_first_install': '🎁 Cadeau de première installation',
        'vip_entry_redeemed': 'VIP %1$d jours',
        'vip_verifying_title': 'Vérification…',
        'vip_success_title': 'Succès',
        'vip_failed_title': 'Échec',
        'privacy_policy': 'Politique de confidentialité',
        'confirm': 'Confirmer',
        'ok': 'OK'
    },
    'values-hi': {
        'vip_active': 'वीआईपी सक्रिय',
        'vip_free_user': 'मुफ़्त उपयोगकर्ता',
        'vip_until': 'वैधता: %1$s तक',
        'vip_activated_at': 'सक्रिय हुआ: %1$s',
        'vip_expires_at': 'समाप्ति: %1$s',
        'vip_remaining': '%1$d दिन %2$02d घंटे %3$02d मिनट %4$02d सेकंड',
        'vip_redeem_label': 'वीआईपी कुंजी दर्ज करें',
        'vip_redeem_hint': 'जैसे LOITP_30',
        'vip_redeem_button': 'सक्रिय करें',
        'vip_watch_ad_3d': 'विज्ञापन देखें → 3 दिन वीआईपी',
        'vip_buy_30d_locked': '30 दिन का वीआईपी खरीदें — जल्द ही आ रहा है',
        'vip_buy_90d_locked': '90 दिन का वीआईपी खरीदें — जल्द ही आ रहा है',
        'vip_buy_1y_locked': '1 साल का वीआईपी खरीदें — जल्द ही आ रहा है',
        'vip_buy_lifetime_locked': 'लाइफटाइम वीआईपी खरीदें — जल्द ही आ रहा है',
        'vip_restore_locked': 'खरीदारी पुनर्स्थापित करें — जल्द ही आ रहा है',
        'vip_revoke_all_button': 'वीआईपी वापस लें',
        'vip_revoke_all_confirm_title': 'पुष्टि करें',
        'vip_revoke_all_confirm_message': 'क्या आप वाकई वीआईपी वापस लेना चाहते हैं और मुफ़्त खाते पर जाना चाहते हैं?',
        'vip_entry_first_install': '🎁 पहली बार इंस्टॉल करने का उपहार',
        'vip_entry_redeemed': 'वीआईपी %1$d दिन',
        'vip_verifying_title': 'सत्यापन हो रहा है…',
        'vip_success_title': 'सफल',
        'vip_failed_title': 'अफल',
        'privacy_policy': 'गोपनीयता नीति',
        'confirm': 'पुष्टि करें',
        'ok': 'ठीक है'
    },
    'values-hu-rHU': {
        'vip_active': 'VIP Aktív',
        'vip_free_user': 'Ingyenes felhasználó',
        'vip_until': 'Lejárat: %1$s',
        'vip_activated_at': 'Aktiválva: %1$s',
        'vip_expires_at': 'Lejár: %1$s',
        'vip_remaining': '%1$dn %2$02dó %3$02dp %4$02dmp',
        'vip_redeem_label': 'VIP kód megadása',
        'vip_redeem_hint': 'pl. LOITP_30',
        'vip_redeem_button': 'Aktiválás',
        'vip_watch_ad_3d': 'Nézzen meg egy hirdetést → 3 napos VIP',
        'vip_buy_30d_locked': '30 napos VIP vásárlása — Hamarosan',
        'vip_buy_90d_locked': '90 napos VIP vásárlása — Hamarosan',
        'vip_buy_1y_locked': '1 éves VIP vásárlása — Hamarosan',
        'vip_buy_lifetime_locked': 'Örökéletű VIP vásárlása — Hamarosan',
        'vip_restore_locked': 'Vásárlás visszaállítása — Hamarosan',
        'vip_revoke_all_button': 'VIP visszavonása',
        'vip_revoke_all_confirm_title': 'Visszavonás megerősítése',
        'vip_revoke_all_confirm_message': 'Biztosan vissza szeretné vonni a VIP státuszt, és visszatér az ingyenes fiókhoz?',
        'vip_entry_first_install': '🎁 Első telepítési ajándék',
        'vip_entry_redeemed': 'VIP %1$d nap',
        'vip_verifying_title': 'Ellenőrzés…',
        'vip_success_title': 'Sikeres',
        'vip_failed_title': 'Sikertelen',
        'privacy_policy': 'Adatvédelmi irányelvek',
        'confirm': 'Megerősítés',
        'ok': 'OK'
    },
    'values-in': {
        'vip_active': 'VIP Aktif',
        'vip_free_user': 'Pengguna Gratis',
        'vip_until': 'Hingga: %1$s',
        'vip_activated_at': 'Diaktifkan: %1$s',
        'vip_expires_at': 'Kedaluwarsa: %1$s',
        'vip_remaining': '%1$dh %2$02djam %3$02dmenit %4$02ddetit',
        'vip_redeem_label': 'Masukkan Kunci VIP',
        'vip_redeem_hint': 'misal: LOITP_30',
        'vip_redeem_button': 'Aktifkan',
        'vip_watch_ad_3d': 'Tonton iklan → 3 hari VIP',
        'vip_buy_30d_locked': 'Beli VIP 30 hari — Segera Hadir',
        'vip_buy_90d_locked': 'Beli VIP 90 hari — Segera Hadir',
        'vip_buy_1y_locked': 'Beli VIP 1 tahun — Segera Hadir',
        'vip_buy_lifetime_locked': 'Beli VIP Selamanya — Segera Hadir',
        'vip_restore_locked': 'Pulihkan Pembelian — Segera Hadir',
        'vip_revoke_all_button': 'Cabut VIP',
        'vip_revoke_all_confirm_title': 'Konfirmasi Pencabutan',
        'vip_revoke_all_confirm_message': 'Apakah Anda yakin ingin mencabut VIP dan kembali ke akun Gratis?',
        'vip_entry_first_install': '🎁 Hadiah Pemasangan Pertama',
        'vip_entry_redeemed': 'VIP %1$d Hari',
        'vip_verifying_title': 'Memverifikasi…',
        'vip_success_title': 'Berhasil',
        'vip_failed_title': 'Gagal',
        'privacy_policy': 'Kebijakan Privasi',
        'confirm': 'Konfirmasi',
        'ok': 'OK'
    },
    'values-it-rIT': {
        'vip_active': 'VIP Attivo',
        'vip_free_user': 'Utente gratuito',
        'vip_until': 'Fino al: %1$s',
        'vip_activated_at': 'Attivato il: %1$s',
        'vip_expires_at': 'Scade il: %1$s',
        'vip_remaining': '%1$dg %2$02dor %3$02dmin %4$02dsec',
        'vip_redeem_label': 'Inserisci codice VIP',
        'vip_redeem_hint': 'es. LOITP_30',
        'vip_redeem_button': 'Attiva',
        'vip_watch_ad_3d': 'Guarda un annuncio → 3 giorni VIP',
        'vip_buy_30d_locked': 'Acquista VIP 30 giorni — Prossimamente',
        'vip_buy_90d_locked': 'Acquista VIP 90 giorni — Prossimamente',
        'vip_buy_1y_locked': 'Acquista VIP 1 anno — Prossimamente',
        'vip_buy_lifetime_locked': 'Acquista VIP a vita — Prossimamente',
        'vip_restore_locked': 'Ripristina acquisti — Prossimamente',
        'vip_revoke_all_button': 'Revoca VIP',
        'vip_revoke_all_confirm_title': 'Conferma revoca',
        'vip_revoke_all_confirm_message': 'Sei sicuro di voler revocare il VIP e tornare a un account gratuito?',
        'vip_entry_first_install': '🎁 Regalo prima installazione',
        'vip_entry_redeemed': 'VIP %1$d giorni',
        'vip_verifying_title': 'Verifica in corso…',
        'vip_success_title': 'Successo',
        'vip_failed_title': 'Fallito',
        'privacy_policy': 'Informativa sulla privacy',
        'confirm': 'Conferma',
        'ok': 'OK'
    },
    'values-iw': {
        'vip_active': 'חבר VIP פעיל',
        'vip_free_user': 'משתמש חינמי',
        'vip_until': 'עד: %1$s',
        'vip_activated_at': 'הופעל ב: %1$s',
        'vip_expires_at': 'פג תוקף ב: %1$s',
        'vip_remaining': '%1$d ימים %2$02d שעות %3$02d דקות %4$02d שניות',
        'vip_redeem_label': 'הזן קוד VIP',
        'vip_redeem_hint': 'למשל: LOITP_30',
        'vip_redeem_button': 'הפעל',
        'vip_watch_ad_3d': 'צפה בפרסומת ← 3 ימי VIP',
        'vip_buy_30d_locked': 'רכישת 30 ימי VIP — בקרוב',
        'vip_buy_90d_locked': 'רכישת 90 ימי VIP — בקרוב',
        'vip_buy_1y_locked': 'רכישת VIP לשנה — בקרוב',
        'vip_buy_lifetime_locked': 'רכישת VIP לכל החיים — בקרוב',
        'vip_restore_locked': 'שחזור רכישות — בקרוב',
        'vip_revoke_all_button': 'בטל VIP',
        'vip_revoke_all_confirm_title': 'אישור ביטול',
        'vip_revoke_all_confirm_message': 'האם אתה בטוח שברצונך לבטל את ה-VIP ולחזור למשתמש חינמי?',
        'vip_entry_first_install': '🎁 מתנת התקנה ראשונה',
        'vip_entry_redeemed': 'VIP ל-%1$d ימים',
        'vip_verifying_title': 'מאמת קוד…',
        'vip_success_title': 'הצלחה',
        'vip_failed_title': 'שגיאה',
        'privacy_policy': 'מדיניות פרטיות',
        'confirm': 'אשר',
        'ok': 'אישור'
    },
    'values-ja-rJP': {
        'vip_active': 'VIP有効',
        'vip_free_user': '無料ユーザー',
        'vip_until': '期限: %1$s',
        'vip_activated_at': '有効化日時: %1$s',
        'vip_expires_at': '期限切れ日時: %1$s',
        'vip_remaining': '%1$d日 %2$02d時間 %3$02d分 %4$02d秒',
        'vip_redeem_label': 'VIPキーを入力',
        'vip_redeem_hint': '例：LOITP_30',
        'vip_redeem_button': '有効化',
        'vip_watch_ad_3d': '広告を見る → 3日間VIP',
        'vip_buy_30d_locked': '30日間VIPを購入 — まもなく公開',
        'vip_buy_90d_locked': '90日間VIPを購入 — まもなく公開',
        'vip_buy_1y_locked': '1年間VIPを購入 — まもなく公開',
        'vip_buy_lifetime_locked': '永久VIPを購入 — まもなく公開',
        'vip_restore_locked': '購入を復元 — まもなく公開',
        'vip_revoke_all_button': 'VIP権限を取り消す',
        'vip_revoke_all_confirm_title': '取り消しの確認',
        'vip_revoke_all_confirm_message': '本当にVIP権限を取り消して、無料アカウントに戻しますか？',
        'vip_entry_first_install': '🎁 新規インストール特典',
        'vip_entry_redeemed': 'VIP %1$d日間',
        'vip_verifying_title': '検証中…',
        'vip_success_title': '成功',
        'vip_failed_title': '失敗',
        'privacy_policy': 'プライバシーポリシー',
        'confirm': '確認',
        'ok': 'OK'
    },
    'values-nb-rNO': {
        'vip_active': 'VIP Aktiv',
        'vip_free_user': 'Gratis bruker',
        'vip_until': 'Til: %1$s',
        'vip_activated_at': 'Aktivert: %1$s',
        'vip_expires_at': 'Utløper: %1$s',
        'vip_remaining': '%1$dd %2$02dt %3$02dm %4$02ds',
        'vip_redeem_label': 'Skriv inn VIP-nøkkel',
        'vip_redeem_hint': 'f.eks. LOITP_30',
        'vip_redeem_button': 'Aktiver',
        'vip_watch_ad_3d': 'Se annonse → 3 dager VIP',
        'vip_buy_30d_locked': 'Kjøp 30 dagers VIP — Kommer snart',
        'vip_buy_90d_locked': 'Kjøp 90 dagers VIP — Kommer snart',
        'vip_buy_1y_locked': 'Kjøp 1 års VIP — Kommer snart',
        'vip_buy_lifetime_locked': 'Kjøp Livstids VIP — Kommer snart',
        'vip_restore_locked': 'Gjenopprett kjøp — Kommer snart',
        'vip_revoke_all_button': 'Fjern VIP',
        'vip_revoke_all_confirm_title': 'Bekreft fjerning',
        'vip_revoke_all_confirm_message': 'Er du sikker på at du vil fjerne VIP og gå tilbake til en gratis konto?',
        'vip_entry_first_install': '🎁 Gave ved første installasjon',
        'vip_entry_redeemed': 'VIP %1$d dager',
        'vip_verifying_title': 'Verifiserer…',
        'vip_success_title': 'Vellykket',
        'vip_failed_title': 'Mislyktes',
        'privacy_policy': 'Personvernerklæring',
        'confirm': 'Bekreft',
        'ok': 'OK'
    },
    'values-nl-rNL': {
        'vip_active': 'VIP Actief',
        'vip_free_user': 'Gratis gebruiker',
        'vip_until': 'Vervalt op: %1$s',
        'vip_activated_at': 'Geactiveerd: %1$s',
        'vip_expires_at': 'Vervalt: %1$s',
        'vip_remaining': '%1$dd %2$02du %3$02dm %4$02ds',
        'vip_redeem_label': 'VIP-sleutel invoeren',
        'vip_redeem_hint': 'bijv. LOITP_30',
        'vip_redeem_button': 'Activeren',
        'vip_watch_ad_3d': 'Advertentie bekijken → 3 dagen VIP',
        'vip_buy_30d_locked': 'Koop 30-dagen VIP — Binnenkort beschikbaar',
        'vip_buy_90d_locked': 'Koop 90-dagen VIP — Binnenkort beschikbaar',
        'vip_buy_1y_locked': 'Koop 1-jaar VIP — Binnenkort beschikbaar',
        'vip_buy_lifetime_locked': 'Koop Levenslang VIP — Binnenkort beschikbaar',
        'vip_restore_locked': 'Aankoop herstellen — Binnenkort beschikbaar',
        'vip_revoke_all_button': 'VIP intrekken',
        'vip_revoke_all_confirm_title': 'Intrekking bevestigen',
        'vip_revoke_all_confirm_message': 'Weet je zeker dat je VIP wilt intrekken en wilt terugkeren naar een gratis account?',
        'vip_entry_first_install': '🎁 Eerste installatie cadeau',
        'vip_entry_redeemed': 'VIP %1$d dagen',
        'vip_verifying_title': 'Verifiëren…',
        'vip_success_title': 'Succes',
        'vip_failed_title': 'Mislukt',
        'privacy_policy': 'Privacybeleid',
        'confirm': 'Bevestigen',
        'ok': 'OK'
    },
    'values-pt-rBR': {
        'vip_active': 'VIP Ativo',
        'vip_free_user': 'Usuário gratuito',
        'vip_until': 'Até: %1$s',
        'vip_activated_at': 'Ativado: %1$s',
        'vip_expires_at': 'Expira: %1$s',
        'vip_remaining': '%1$dd %2$02dh %3$02dm %4$02ds',
        'vip_redeem_label': 'Inserir chave VIP',
        'vip_redeem_hint': 'ex. LOITP_30',
        'vip_redeem_button': 'Ativar',
        'vip_watch_ad_3d': 'Assistir anúncio → 3 dias VIP',
        'vip_buy_30d_locked': 'Comprar VIP 30 dias — Em breve',
        'vip_buy_90d_locked': 'Comprar VIP 90 dias — Em breve',
        'vip_buy_1y_locked': 'Comprar VIP 1 ano — Em breve',
        'vip_buy_lifetime_locked': 'Comprar VIP vitalício — Em breve',
        'vip_restore_locked': 'Restaurar compra — Em breve',
        'vip_revoke_all_button': 'Revogar VIP',
        'vip_revoke_all_confirm_title': 'Confirmar revogação',
        'vip_revoke_all_confirm_message': 'Tem certeza de que deseja revogar o VIP e voltar para uma conta gratuita?',
        'vip_entry_first_install': '🎁 Presente de primeira instalação',
        'vip_entry_redeemed': 'VIP %1$d dias',
        'vip_verifying_title': 'Verificando…',
        'vip_success_title': 'Sucesso',
        'vip_failed_title': 'Falhou',
        'privacy_policy': 'Política de privacidade',
        'confirm': 'Confirmar',
        'ok': 'OK'
    },
    'values-pt-rPT': {
        'vip_active': 'VIP Ativo',
        'vip_free_user': 'Utilizador gratuito',
        'vip_until': 'Até: %1$s',
        'vip_activated_at': 'Ativado: %1$s',
        'vip_expires_at': 'Expira: %1$s',
        'vip_remaining': '%1$dd %2$02dh %3$02dm %4$02ds',
        'vip_redeem_label': 'Inserir chave VIP',
        'vip_redeem_hint': 'ex. LOITP_30',
        'vip_redeem_button': 'Ativar',
        'vip_watch_ad_3d': 'Assistir anúncio → 3 dias VIP',
        'vip_buy_30d_locked': 'Comprar VIP 30 dias — Brevemente',
        'vip_buy_90d_locked': 'Comprar VIP 90 dias — Brevemente',
        'vip_buy_1y_locked': 'Comprar VIP 1 ano — Brevemente',
        'vip_buy_lifetime_locked': 'Comprar VIP vitalício — Brevemente',
        'vip_restore_locked': 'Restaurar compra — Brevemente',
        'vip_revoke_all_button': 'Revogar VIP',
        'vip_revoke_all_confirm_title': 'Confirmar revogação',
        'vip_revoke_all_confirm_message': 'Tem a certeza de que deseja revogar o VIP e voltar para uma conta gratuita?',
        'vip_entry_first_install': '🎁 Presente de primeira instalação',
        'vip_entry_redeemed': 'VIP %1$d dias',
        'vip_verifying_title': 'A verificar…',
        'vip_success_title': 'Sucesso',
        'vip_failed_title': 'Falhou',
        'privacy_policy': 'Política de privacidade',
        'confirm': 'Confirmar',
        'ok': 'OK'
    },
    'values-ru-rRU': {
        'vip_active': 'VIP Активен',
        'vip_free_user': 'Обычный пользователь',
        'vip_until': 'До: %1$s',
        'vip_activated_at': 'Активировано: %1$s',
        'vip_expires_at': 'Истекает: %1$s',
        'vip_remaining': '%1$dд %2$02дч %3$02дм %4$02дс',
        'vip_redeem_label': 'Введите VIP ключ',
        'vip_redeem_hint': 'напр. LOITP_30',
        'vip_redeem_button': 'Активировать',
        'vip_watch_ad_3d': 'Посмотреть рекламу → 3 дня VIP',
        'vip_buy_30d_locked': 'Купить 30 дней VIP — Скоро',
        'vip_buy_90d_locked': 'Купить 90 дней VIP — Скоро',
        'vip_buy_1y_locked': 'Купить 1 год VIP — Скоро',
        'vip_buy_lifetime_locked': 'Купить пожизненный VIP — Скоро',
        'vip_restore_locked': 'Восстановить покупки — Скоро',
        'vip_revoke_all_button': 'Аннулировать VIP',
        'vip_revoke_all_confirm_title': 'Подтверждение',
        'vip_revoke_all_confirm_message': 'Вы уверены, что хотите аннулировать VIP и вернуться на бесплатную версию?',
        'vip_entry_first_install': '🎁 Подарок при первой установке',
        'vip_entry_redeemed': 'VIP на %1$d дн.',
        'vip_verifying_title': 'Проверка ключа…',
        'vip_success_title': 'Успешно',
        'vip_failed_title': 'Ошибка',
        'privacy_policy': 'Политика конфиденциальности',
        'confirm': 'Подтвердить',
        'ok': 'OK'
    },
    'values-tr-rTR': {
        'vip_active': 'VIP Aktif',
        'vip_free_user': 'Ücretsiz Kullanıcı',
        'vip_until': 'Son kullanma: %1$s',
        'vip_activated_at': 'Etkinleştirildi: %1$s',
        'vip_expires_at': 'Bitiş: %1$s',
        'vip_remaining': '%1$dg %2$02ds %3$02dd %4$02ds',
        'vip_redeem_label': 'VIP Kodu Girin',
        'vip_redeem_hint': 'örn: LOITP_30',
        'vip_redeem_button': 'Etkinleştir',
        'vip_watch_ad_3d': 'Reklam izle → 3 günlük VIP',
        'vip_buy_30d_locked': '30 günlük VIP satın al — Yakında',
        'vip_buy_90d_locked': '90 günlük VIP satın al — Yakında',
        'vip_buy_1y_locked': '1 yıllık VIP satın al — Yakında',
        'vip_buy_lifetime_locked': 'Ömür boyu VIP satın al — Yakında',
        'vip_restore_locked': 'Satın alımları geri yükle — Yakında',
        'vip_revoke_all_button': 'VIP Geri Al',
        'vip_revoke_all_confirm_title': 'Geri almayı onayla',
        'vip_revoke_all_confirm_message': 'VIP üyeliği iptal edip ücretsiz hesaba geri dönmek istediğinizden emin misiniz?',
        'vip_entry_first_install': '🎁 İlk Kurulum Hediyesi',
        'vip_entry_redeemed': 'VIP %1$d Gün',
        'vip_verifying_title': 'Doğrulanıyor…',
        'vip_success_title': 'Başarılı',
        'vip_failed_title': 'Başarısız',
        'privacy_policy': 'Gizlilik Politikası',
        'confirm': 'Onayla',
        'ok': 'Tamam'
    },
    'values-zh-rCN': {
        'vip_active': 'VIP已激活',
        'vip_free_user': '免费用户',
        'vip_until': '至：%1$s',
        'vip_activated_at': '激活于：%1$s',
        'vip_expires_at': '过期于：%1$s',
        'vip_remaining': '%1$d天 %2$02d小时 %3$02d分 %4$02d秒',
        'vip_redeem_label': '输入 VIP 激活码',
        'vip_redeem_hint': '例如: LOITP_30',
        'vip_redeem_button': '激活',
        'vip_watch_ad_3d': '观看广告 → 3天VIP',
        'vip_buy_30d_locked': '购买30天VIP — 即将推出',
        'vip_buy_90d_locked': '购买90天VIP — 即将推出',
        'vip_buy_1y_locked': '购买1年VIP — 即将推出',
        'vip_buy_lifetime_locked': '购买永久VIP — 即将推出',
        'vip_restore_locked': '恢复购买 — 即将推出',
        'vip_revoke_all_button': '撤销 VIP',
        'vip_revoke_all_confirm_title': '确认撤销',
        'vip_revoke_all_confirm_message': '您确定要撤销 VIP 并返回免费账户吗？',
        'vip_entry_first_install': '🎁 首入礼包',
        'vip_entry_redeemed': 'VIP %1$d 天',
        'vip_verifying_title': '验证中…',
        'vip_success_title': '成功',
        'vip_failed_title': '失败',
        'privacy_policy': '隐私政策',
        'confirm': '确认',
        'ok': '确定'
    }
}

base_dir = "/Users/loitran/AndroidStudioProjects/@mckimquyen/@playstore/@prodution/@ad/260405_HexViewer/app/src/main/res"

for folder, strings_dict in translations.items():
    file_path = os.path.join(base_dir, folder, "strings.xml")
    if os.path.exists(file_path):
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Check if already inserted to prevent duplication
        if 'vip_active' in content:
            print(f"Skipping {folder}, VIP strings already updated.")
            continue
            
        insertion = "\n    <!-- VIP Strings -->\n"
        for key, value in strings_dict.items():
            # Escape single quotes and question marks for Android XML string resources
            escaped_val = value.replace("'", "\\'").replace("?", "\\?")
            insertion += f'    <string name="{key}">{escaped_val}</string>\n'
            
        new_content = content.replace("</resources>", f"{insertion}</resources>")
        
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(new_content)
        print(f"Updated {folder}/strings.xml")
